name: ELFCOST 编译与测试（Linux/macOS）

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]  # 仅聚焦当前可落地的平台

    steps:
    - name: 拉取代码
      uses: actions/checkout@v4

    - name: 安装依赖（仅Linux）
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get update && sudo apt-get install -y gcc make

    - name: 编译编译器（debug模式）
      run: make debug && ls -lh elfc-compiler-dbg  # 验证编译产物

    - name: 运行单元测试（词法/语法分析）
      run: make test && ./tests/runner  # 仅测试通用模块，不依赖E-comOS

    - name: 测试示例代码（生成通用裸机二进制）
      run: |
        # 编译通用嵌入式示例（不涉及E-comOS专属硬件）
        ./elfc-compiler-dbg examples/x86_real_boot.elfc boot.bin  # x86实模式启动代码
        ./elfc-compiler-dbg examples/uart_demo.elfc uart.bin      # 通用UART测试
        ./elfc-compiler-dbg examples/mbr_template.elfc mbr.bin    # 通用MBR模板

        # 验证MBR二进制规范（通用裸机要求，不依赖E-comOS）
        if [ $(uname) = "Linux" ]; then
          file_size=$(stat -c%s mbr.bin)
        else
          file_size=$(stat -f%z mbr.bin)
        fi
        if [ $file_size -ne 512 ]; then
          echo "错误：MBR文件大小应为512字节，实际为$file_size字节"
          exit 1
        fi

        # 验证MBR签名（0xaa55）
        signature=$(dd if=mbr.bin bs=1 skip=510 count=2 2>/dev/null | xxd -p)
        if [ "$signature" != "aa55" ]; then
          echo "错误：MBR签名应为aa55，实际为$signature"
          exit 1
        fi
